import {
  WifiIcon,
  TvIcon,
  WrenchScrewdriverIcon,
  ArrowDownOnSquareIcon,
  MapPinIcon,
  AdjustmentsHorizontalIcon,
  CubeIcon,
  BeakerIcon,
  SparklesIcon,
  BuildingOffice2Icon,
  FireIcon,
  HomeModernIcon,
  SunIcon,
  BriefcaseIcon,
  UsersIcon,
  EyeIcon,
  BookOpenIcon,
  EyeDropperIcon,
} from "@heroicons/react/24/outline";

const amenityIcons = {
  WiFi: WifiIcon,
  TV: TvIcon,
  Kitchen: WrenchScrewdriverIcon,
  "Washing Machine": ArrowDownOnSquareIcon,
  Parking: MapPinIcon,
  Iron: AdjustmentsHorizontalIcon,
  "Mini fridge": CubeIcon,
  "Coffee maker": BeakerIcon,
  "Air conditioning": SparklesIcon,
  Elevator: BuildingOffice2Icon,
  Dryer: ArrowDownOnSquareIcon,
  Fireplace: FireIcon,
  Garden: HomeModernIcon,
  "Beach access": SunIcon,
  Desk: BriefcaseIcon,
  BBQ: FireIcon,
  "Outdoor seating": UsersIcon,
  "Infinity pool": EyeIcon,
  "Ski-in/Ski-out": SunIcon,
  "Work desk": BriefcaseIcon,
  "Banquet hall": UsersIcon,
  Library: BookOpenIcon,
  Gardens: HomeModernIcon,
  "Lake view": EyeDropperIcon,
  "Hot tub": SparklesIcon,
};

export default amenityIcons;
